### PR TITLE
Refactor FA folder

### PR DESCRIPTION
**Pull request by DidierRLopes**
This PR contains:
- Refactor overall FA code (according to #26 and #53)
- Fix all Market Watch web scraping commands
- Fix quote FMP API call

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Sorry for spam. Not sure why lint is complaining:

```
03:18 $ pylint gamestonk_terminal/fundamental_analysis/financial_modeling_prep_api.py 

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

**Comment by aia** [comment]
You will want to do this a different way.

Merge didn't quite figure things out the right way.

I can show you if you like.

**Comment by aia** [comment]
You want to back off main and than pick and apply diffs:
https://patch-diff.githubusercontent.com/raw/DidierRLopes/GamestonkTerminal/pull/26.diff
https://github.com/DidierRLopes/GamestonkTerminal/pull/53.diff

I would also do it bit by bit, one PR at a time.

**Comment by cclauss** [comment]
`28    E501 line too long (692 > 140 characters)`

flake8 is running with `--max-line-length=140` when [the usual setting to match `psf/black --line-length ` should be 82](https://github.com/psf/black#command-line-options) characters per line.  My sense is that the absolute upper limit should be 127 to avoid left-right scrolling when reading code on GitHub.  Perhaps these large blocks of text should be read in from external files like .txt, .yml, .toml, .po, .json, etc.

**Comment by aia** [comment]
Actually, that is true. You only have a few lines where text blocks got merged into a single long line.

**Comment by aia** [comment]
Line-break

**Comment by aia** [comment]
pylint will break on it too - max-line-length=140 in .pylintrc

**Comment by DidierRLopes** [comment]
> pylint will break on it too - max-line-length=140 in .pylintrc

I thought that these settings would deal with such issues.

Captura de ecrã 2021-03-06, às 09 37 40

**Comment by cclauss** [comment]
`grep -r "# -------" .`

;-)

**Review by aia — APPROVED** [review]

**Comment by aia** [comment]
I'll take a liberty to merge several of the PRs that are ready.

**Pull request merged**
