### PR TITLE
Added scaling to arima, ets, fbprophet, knn, nn, regression, sma and historical yahoo_finance_api

### PR DESCRIPTION
**Pull request by buzzCraft**
Added scaling to arima, ets, fbprophet, knn, nn, regression, sma and historical yahoo_finance_api.
Left corr at yahoo-finance_api untouched, as i think corr maps work best as squares.

### CODE REVIEW

**Comment by buzzCraft** [comment]
Seems like I got wrong version of neural_networks.py.. Tried to fix it but probably just made a mess :P

**Comment by DidierRLopes** [comment]
Yea, it seems there are still conflicts. The best way to go about this is to try to merge the main branch onto yours and make sure you resolved all conflicts.

If you do `git pull` on VSCode you'll see that it will fail to pull because it has conflicts. You need to fix these one by one (usually you can see the blue/green color on the right scrollbar), and commit that after. And that should be it.

Let me know if you need help with this :)

**Comment by buzzCraft** [comment]
Ok, conflict is resolved.

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Amazing, thank you for this @buzzCraft !

**Pull request merged**
