### PR TITLE
docker image: fix install

### PR DESCRIPTION
**Pull request by gregwebs**
The existing docker image immediately has errors on startup when I ran it. Installing requirements-full fixed that.

### CODE REVIEW

**Comment by aia** [comment]
Your pull request is removing poetry (our selected dependency management framework) and installing full dependencies instead of the standard dependencies that exclude ML.

What problems are you having with docker?

**Comment by gregwebs** [comment]
This is using a cached list of dependencies already existing in the repo. So I would presume that this is not "removing poetry" but instead using a cache that was generated by poetry?

Here is what happens with the existing docker image on master. Have you tried running it?

```
docker run --rm -it gamestonkterminal:dev
     code/GamestonkTerminal  main
Traceback (most recent call last):
  File "terminal.py", line 27, in <module>
    from gamestonk_terminal.exploratory_data_analysis import eda_controller
  File "/home/python/gamestonk_terminal/exploratory_data_analysis/eda_controller.py", line 9, in <module>
    from gamestonk_terminal.exploratory_data_analysis import eda_api
  File "/home/python/gamestonk_terminal/exploratory_data_analysis/eda_api.py", line 13, in <module>
    import statsmodels.api as sm
ModuleNotFoundError: No module named 'statsmodels'
```

**Comment by aia** [comment]
That error suggests that we are missing statsmodels from https://github.com/DidierRLopes/GamestonkTerminal/blob/main/pyproject.toml

**Comment by aia** [comment]
The issue should be addressed now. Please try running the docker.

**Comment by gregwebs** [comment]
Thanks, that works!

**Pull request closed without merging**
