### PR TITLE
Options - volume working 

### PR DESCRIPTION
**Pull request by lolrenx**
options menu added 
working feature for now : volume graph 

```
load TICKER 
op 
volume -e EXPIRYDATE 
```

### CODE REVIEW

**Comment by DidierRLopes** [comment]
I resolved the conflicts with the merge of #199.

**Comment by lolrenx** [comment]
> I resolved the conflicts with the merge of #199.

cheers. 
Something weird happening on my side now though, on open  :

```
Traceback (most recent call last):
  File "terminal.py", line 12, in <module>
    from gamestonk_terminal import config_terminal as cfg
  File "/Users/laurent/projects/GamestonkTerminal/gamestonk_terminal/__init__.py", line 2, in <module>
    from . import discovery
  File "/Users/laurent/projects/GamestonkTerminal/gamestonk_terminal/discovery/__init__.py", line 1, in <module>
    from . import disc_menu  # noqa: F401
  File "/Users/laurent/projects/GamestonkTerminal/gamestonk_terminal/discovery/disc_menu.py", line 3, in <module>
    from gamestonk_terminal.discovery import (
  File "/Users/laurent/projects/GamestonkTerminal/gamestonk_terminal/discovery/alpha_vantage_api.py", line 5, in <module>
    from gamestonk_terminal.helper_funcs import parse_known_args_and_warn
  File "/Users/laurent/projects/GamestonkTerminal/gamestonk_terminal/helper_funcs.py", line 14, in <module>
    from screeninfo import get_monitors
ModuleNotFoundError: No module named 'screeninfo'
```

**Comment by jmaslek** [comment]
I had that issue after the autoscaling PR was merged.  I did pip install screeninfo  .  Maybe that needs to be added to the poetry lock?

**Comment by lolrenx** [comment]
> I had that issue after the autoscaling PR was merged. I did pip install screeninfo . Maybe that needs to be added to the poetry lock?

yes, had to `pip install screeninfo and fredapi `

thought that would be updated to the requirements

**Comment by buzzCraft** [comment]
> 
> 
> > I had that issue after the autoscaling PR was merged. I did pip install screeninfo . Maybe that needs to be added to the poetry lock?
> 
> yes, had to `pip install screeninfo and fredapi `
> 
> thought that would be updated to the requirements

It got added to poetry lock and requirements. Did you do a requirement install after it got introduced?

**Review by aia — APPROVED** [review]

**Comment by aia** [comment]
Great work!

**Comment by lolrenx** [comment]
> Great work!

Thanks ! Really excited about all that !

**Pull request merged**
