### PR TITLE
introduce latest ratings changes from MarketBeat

### PR DESCRIPTION
**Pull request by hinxx**
It might be interesting to see how the stock's ratings change. TBH, I'm not really looking at this data myself, I just wanted to gain some practice in adding new features/commands to GST :rofl: .

MarketBeat has a page that shows this https://www.marketbeat.com/ratings/.

I've added a new entry to discovery menu, called 'ratings'.
```
   ratings        latest ratings [MarketBeat]
```

It lists the entries scrapped from the above web page. No filters are applied, ATM. Example output:
```
(✨) (disc)> ratings
AA  Target Raised Medium $32.84 -> $36.00 ➝ $38.00
AAWW  Initiated Low $65.71 ->  $95.00
ACVA  Initiated Low $36.83 ->  $34.00
ADS  Target Set N/A €277.55 ->  €300.00
AEO  Target Raised Low $34.33 -> $25.00 ➝ $27.00
AFRM  Upgraded Medium $68.67 ->  $80.00
AIR  Target Set N/A €102.84 ->  €110.00
AIR  Target Set N/A €102.84 ->  €125.00
ALL  Target Raised Low $121.59 -> $119.00 ➝ $128.00
ALV  Target Set N/A €215.45 ->  €250.00
```

Formatting is not optimal and not all columns seen on the web page are printed (they are scrapped and available for printing, though).

BTW, It might be possible to add per-ticker filtered ratings command to only look up the ratings for the loaded ticker. Thoughts?

Comments welcomed!

### CODE REVIEW

**Comment by DidierRLopes** [comment]
> It might be interesting to see how the stock's ratings change. TBH, I'm not really looking at this data myself, I just wanted to gain some practice in adding new features/commands to GST 🤣 .
> 
> MarketBeat has a page that shows this https://www.marketbeat.com/ratings/.
> 
> I've added a new entry to discovery menu, called 'ratings'.
> 
> ```
>    ratings        latest ratings [MarketBeat]
> ```
> 
> It lists the entries scrapped from the above web page. No filters are applied, ATM. Example output:
> 
> ```
> (✨) (disc)> ratings
> AA  Target Raised Medium $32.84 -> $36.00 ➝ $38.00
> AAWW  Initiated Low $65.71 ->  $95.00
> ACVA  Initiated Low $36.83 ->  $34.00
> ADS  Target Set N/A €277.55 ->  €300.00
> AEO  Target Raised Low $34.33 -> $25.00 ➝ $27.00
> AFRM  Upgraded Medium $68.67 ->  $80.00
> AIR  Target Set N/A €102.84 ->  €110.00
> AIR  Target Set N/A €102.84 ->  €125.00
> ALL  Target Raised Low $121.59 -> $119.00 ➝ $128.00
> ALV  Target Set N/A €215.45 ->  €250.00
> ```
> 
> Formatting is not optimal and not all columns seen on the web page are printed (they are scrapped and available for printing, though).
> 
> BTW, It might be possible to add per-ticker filtered ratings command to only look up the ratings for the loaded ticker. Thoughts?
> 
> Comments welcomed!

Again, I really like this idea!

My comments are:
* Same, have been so busy adding features to the terminal that haven't been able to use it again. Hard work will pay off at some point eheh
* Ratings for a particular ticker is already handled by these commands on `dd`:
```
analyst       analyst prices and ratings of the company [Finviz]
rating        rating of the company from strong sell to strong buy [FMP]
pt            price targets over time [Business Insider]
```
* I like the information you have here because it's daily. But my main concern is that if we print all ratings that occurred on the day, we will lose ourselves in the noise. Let me have a look at how we can improve the user experience. I was thinking instead of limiting stocks per alphabet, list by "price target change".

**Comment by DidierRLopes** [comment]
ratings

I think it looks really nice!! And it definitely flags the big leaps

**Comment by DidierRLopes** [comment]
See https://github.com/hinxx/GamestonkTerminal/pull/3

**Comment by hinxx** [comment]
Thanks for taking the time and effort in improving this PR.
I missed the other commands that deal with the ratings; so many features so little time to use them all :D.
I agree with the goal of this command is showing the top few sorted by % change, across the market.

**Review by aia — APPROVED** [review]

**Comment by DidierRLopes** [comment]
I think the commits I've made merged to your main branch rather than your marketbeat-ratings one :(

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Let me try to have a go if I can get them back and do a PR for this branch

**Comment by DidierRLopes** [comment]
I've made a mess here, #357 should replace this PR!

**Comment by hinxx** [comment]
No worries m8! It's just bits .. ;)

**Pull request closed without merging**
