### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by aia**
fix-build

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]
Thanks for removing my key! Although I think that now Polygon isn't really used, since similar companies are much better from Finviz :)

Why did this not flag when I created the PR? Did we change something in the meanwhile in the build?

**Comment by aia** [comment]
Pyupgrade released a new version
```
pip install pyupgrade -U
Requirement already satisfied: pyupgrade in /home/artem/.pyenv/versions/miniconda3-latest/envs/gst2/lib/python3.8/site-packages (2.11.0)
Collecting pyupgrade
  Downloading pyupgrade-2.12.0-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 1.1 MB/s
Requirement already satisfied: tokenize-rt>=3.2.0 in /home/artem/.pyenv/versions/miniconda3-latest/envs/gst2/lib/python3.8/site-packages (from pyupgrade) (4.1.0)
Installing collected packages: pyupgrade
  Attempting uninstall: pyupgrade
    Found existing installation: pyupgrade 2.11.0
    Uninstalling pyupgrade-2.11.0:
      Successfully uninstalled pyupgrade-2.11.0
Successfully installed pyupgrade-2.12.0
```

**Comment by DidierRLopes** [comment]
> Pyupgrade released a new version
> 
> ```
> 
> pip install pyupgrade -U
> 
> Requirement already satisfied: pyupgrade in /home/artem/.pyenv/versions/miniconda3-latest/envs/gst2/lib/python3.8/site-packages (2.11.0)
> 
> Collecting pyupgrade
> 
>   Downloading pyupgrade-2.12.0-py2.py3-none-any.whl (46 kB)
> 
>      |████████████████████████████████| 46 kB 1.1 MB/s
> 
> Requirement already satisfied: tokenize-rt>=3.2.0 in /home/artem/.pyenv/versions/miniconda3-latest/envs/gst2/lib/python3.8/site-packages (from pyupgrade) (4.1.0)
> 
> Installing collected packages: pyupgrade
> 
>   Attempting uninstall: pyupgrade
> 
>     Found existing installation: pyupgrade 2.11.0
> 
>     Uninstalling pyupgrade-2.11.0:
> 
>       Successfully uninstalled pyupgrade-2.11.0
> 
> Successfully installed pyupgrade-2.12.0
> 
> ```

Got you! Cheers!

**Comment by jmaslek** [comment]
Im confused.  Did I break it?  I thought my last commit passed the checks

**Comment by aia** [comment]
> Im confused. Did I break it? I thought my last commit passed the checks

No, you were an unfortunate victim of the new pyupgrade version.

**Pull request merged**
