### PR TITLE
Add ark_view unit test

### PR DESCRIPTION
**Pull request by aia**
I started running a coverage report.

We are at 15% :information_desk_person: :speak_no_evil:

```
----------- coverage: platform linux, python 3.8.8-final-0 -----------
Name                                                                     Stmts   Miss  Cover
--------------------------------------------------------------------------------------------
gamestonk_terminal/__init__.py                                               7      0   100%
gamestonk_terminal/behavioural_analysis/__init__.py                          0      0   100%
gamestonk_terminal/behavioural_analysis/ba_controller.py                   129    129     0%
gamestonk_terminal/behavioural_analysis/finbrain_view.py                    73     73     0%
gamestonk_terminal/behavioural_analysis/google_view.py                      86     86     0%
gamestonk_terminal/behavioural_analysis/reddit_view.py                     269    269     0%
gamestonk_terminal/behavioural_analysis/stocktwits_view.py                  92     92     0%
gamestonk_terminal/behavioural_analysis/twitter_view.py                    189    189     0%
gamestonk_terminal/config_neural_network_models.py                           3      0   100%
gamestonk_terminal/config_plot.py                                            6      0   100%
gamestonk_terminal/config_terminal.py                                       17      0   100%
gamestonk_terminal/cryptocurrency/__init__.py                                0      0   100%
gamestonk_terminal/cryptocurrency/coin_api.py                               68     68     0%
gamestonk_terminal/cryptocurrency/crypto_controller.py                      58     58     0%
gamestonk_terminal/cryptocurrency/crypto_helper.py                           8      8     0%
gamestonk_terminal/dataframe_helpers.py                                      4      0   100%
gamestonk_terminal/discovery/__init__.py                                     1      0   100%
gamestonk_terminal/discovery/alpha_vantage_view.py                          23     14    39%
gamestonk_terminal/discovery/ark_model.py                                   37      4    89%
gamestonk_terminal/discovery/ark_view.py                                    39      4    90%
gamestonk_terminal/discovery/disc_controller.py                             80     50    38%
gamestonk_terminal/discovery/fidelity_model.py                              32      1    97%
gamestonk_terminal/discovery/fidelity_view.py                               39      2    95%
gamestonk_terminal/discovery/finviz_view.py                                 16     10    38%
gamestonk_terminal/discovery/seeking_alpha_model.py                         24      2    92%
gamestonk_terminal/discovery/seeking_alpha_view.py                          22     15    32%
gamestonk_terminal/discovery/short_interest_model.py                        44      0   100%
gamestonk_terminal/discovery/short_interest_view.py                         26     18    31%
gamestonk_terminal/discovery/simply_wallst_view.py                          13      7    46%
gamestonk_terminal/discovery/spachero_view.py                               12      6    50%
gamestonk_terminal/discovery/unusual_whales_view.py                         11      6    45%
gamestonk_terminal/discovery/yahoo_finance_view.py                          23     16    30%
gamestonk_terminal/due_diligence/__init__.py                                 0      0   100%
gamestonk_terminal/due_diligence/business_insider_api.py                   207    207     0%
gamestonk_terminal/due_diligence/dd_menu.py                                 78     78     0%
gamestonk_terminal/due_diligence/financial_modeling_prep_api.py             21      6    71%
gamestonk_terminal/due_diligence/finviz_api.py                              75     43    43%
gamestonk_terminal/due_diligence/market_watch_api.py                       152    152     0%
gamestonk_terminal/due_diligence/news_api.py                                25     25     0%
gamestonk_terminal/due_diligence/quandl_api.py                              50     50     0%
gamestonk_terminal/due_diligence/reddit_api.py                              38     38     0%
gamestonk_terminal/feature_flags.py                                          9      0   100%
gamestonk_terminal/fred/__init__.py                                          1      0   100%
gamestonk_terminal/fred/fred_controller.py                                  66     45    32%
gamestonk_terminal/fred/fred_view.py                                        89     56    37%
gamestonk_terminal/fundamental_analysis/__init__.py                          0      0   100%
gamestonk_terminal/fundamental_analysis/alpha_vantage_api.py               209    209     0%
gamestonk_terminal/fundamental_analysis/business_insider_api.py             55     33    40%
gamestonk_terminal/fundamental_analysis/fa_menu.py                         109    109     0%
gamestonk_terminal/fundamental_analysis/financial_modeling_prep_api.py     300    251    16%
gamestonk_terminal/fundamental_analysis/finviz_api.py                       19     19     0%
gamestonk_terminal/fundamental_analysis/market_watch_api.py                 95     44    54%
gamestonk_terminal/fundamental_analysis/yahoo_finance_api.py               115     68    41%
gamestonk_terminal/fundamental_analysis/yield_curve_model.py                35      0   100%
gamestonk_terminal/helper_funcs.py                                         271    159    41%
gamestonk_terminal/main_helper.py                                          194    194     0%
gamestonk_terminal/menu.py                                                  19      7    63%
gamestonk_terminal/papermill/__init__.py                                     1      0   100%
gamestonk_terminal/papermill/due_diligence_view.py                          28     20    29%
gamestonk_terminal/papermill/econ_data_helper.py                            26     26     0%
gamestonk_terminal/papermill/econ_data_view.py                              26     18    31%
gamestonk_terminal/papermill/papermill_controller.py                        46     30    35%
gamestonk_terminal/portfolio/__init__.py                                     0      0   100%
gamestonk_terminal/portfolio/ally_api.py                                    32     32     0%
gamestonk_terminal/portfolio/alp_api.py                                     58     58     0%
gamestonk_terminal/portfolio/port_controller.py                            130    130     0%
gamestonk_terminal/portfolio/portfolio_helpers.py                           58     58     0%
gamestonk_terminal/portfolio/rh_api.py                                      86     86     0%
gamestonk_terminal/prediction_techniques/__init__.py                         0      0   100%
gamestonk_terminal/prediction_techniques/arima.py                          126    126     0%
gamestonk_terminal/prediction_techniques/ets.py                            174    174     0%
gamestonk_terminal/prediction_techniques/fbprophet.py                      113    113     0%
gamestonk_terminal/prediction_techniques/knn.py                            118    118     0%
gamestonk_terminal/prediction_techniques/neural_networks.py                305    272    11%
gamestonk_terminal/prediction_techniques/pred_helper.py                     42     31    26%
gamestonk_terminal/prediction_techniques/pred_menu.py                       76     76     0%
gamestonk_terminal/prediction_techniques/regression.py                     130    130     0%
gamestonk_terminal/prediction_techniques/sma.py                            115    115     0%
gamestonk_terminal/reddit_helpers.py                                        37     37     0%
gamestonk_terminal/res_menu.py                                              93     93     0%
gamestonk_terminal/technical_analysis/__init__.py                            0      0   100%
gamestonk_terminal/technical_analysis/finbrain_view.py                      26     26     0%
gamestonk_terminal/technical_analysis/momentum.py                          187    187     0%
gamestonk_terminal/technical_analysis/overlap.py                           115    115     0%
gamestonk_terminal/technical_analysis/ta_controller.py                     110    110     0%
gamestonk_terminal/technical_analysis/tradingview_view.py                   48     48     0%
gamestonk_terminal/technical_analysis/trend_indicators.py                   98     98     0%
gamestonk_terminal/technical_analysis/trendline_api.py                      26     26     0%
gamestonk_terminal/technical_analysis/volatility.py                         44     44     0%
gamestonk_terminal/technical_analysis/volume.py                             95     95     0%
gamestonk_terminal/test_helper.py                                           29     29     0%
gamestonk_terminal/thought_of_the_day.py                                    60     25    58%
terminal.py                                                                168    168     0%
tests/__init__.py                                                            0      0   100%
tests/test_ba_finbrain_api.py                                                4      0   100%
tests/test_dd_financial_modeling_prep_api.py                                 5      0   100%
tests/test_dd_finviz_api.py                                                  5      0   100%
tests/test_discovery_ark_api.py                                              4      0   100%
tests/test_discovery_ark_model.py                                           23      0   100%
tests/test_discovery_ark_view.py                                            15      0   100%
tests/test_discovery_fidelity_api.py                                        15     15     0%
tests/test_discovery_fidelity_model.py                                      14      0   100%
tests/test_discovery_seeing_alpha_model.py                                  12      0   100%
tests/test_discovery_short_interest_model.py                                20     20     0%
tests/test_fa_business_insider_api.py                                        5      0   100%
tests/test_fa_financial_modeling_prep_api.py                                11     11     0%
tests/test_fa_market_watch_api.py                                            5      0   100%
tests/test_fa_market_watch_api_unit.py                                      13     13     0%
tests/test_fa_yahoo_finance_api.py                                           9      0   100%
tests/test_fa_yield_curve_model.py                                          24     24     0%
tests/test_fred_fred_view.py                                                12      0   100%
tests/test_pred_neural_networks.py                                          18     18     0%
tests/test_sentiment_reddit_api.py                                           4      4     0%
tests/test_thought_of_the_day.py                                            17     17     0%
--------------------------------------------------------------------------------------------
TOTAL                                                                     6744   5756    15%
```

### CODE REVIEW

**Comment by DidierRLopes** [comment]
> I started running a coverage report.
> 
> We are at 15% 💁 🙊
> 
> ```
> ----------- coverage: platform linux, python 3.8.8-final-0 -----------
> Name                                                                     Stmts   Miss  Cover
> --------------------------------------------------------------------------------------------
> gamestonk_terminal/__init__.py                                               7      0   100%
> gamestonk_terminal/behavioural_analysis/__init__.py                          0      0   100%
> gamestonk_terminal/behavioural_analysis/ba_controller.py                   129    129     0%
> gamestonk_terminal/behavioural_analysis/finbrain_view.py                    73     73     0%
> gamestonk_terminal/behavioural_analysis/google_view.py                      86     86     0%
> gamestonk_terminal/behavioural_analysis/reddit_view.py                     269    269     0%
> gamestonk_terminal/behavioural_analysis/stocktwits_view.py                  92     92     0%
> gamestonk_terminal/behavioural_analysis/twitter_view.py                    189    189     0%
> gamestonk_terminal/config_neural_network_models.py                           3      0   100%
> gamestonk_terminal/config_plot.py                                            6      0   100%
> gamestonk_terminal/config_terminal.py                                       17      0   100%
> gamestonk_terminal/cryptocurrency/__init__.py                                0      0   100%
> gamestonk_terminal/cryptocurrency/coin_api.py                               68     68     0%
> gamestonk_terminal/cryptocurrency/crypto_controller.py                      58     58     0%
> gamestonk_terminal/cryptocurrency/crypto_helper.py                           8      8     0%
> gamestonk_terminal/dataframe_helpers.py                                      4      0   100%
> gamestonk_terminal/discovery/__init__.py                                     1      0   100%
> gamestonk_terminal/discovery/alpha_vantage_view.py                          23     14    39%
> gamestonk_terminal/discovery/ark_model.py                                   37      4    89%
> gamestonk_terminal/discovery/ark_view.py                                    39      4    90%
> gamestonk_terminal/discovery/disc_controller.py                             80     50    38%
> gamestonk_terminal/discovery/fidelity_model.py                              32      1    97%
> gamestonk_terminal/discovery/fidelity_view.py                               39      2    95%
> gamestonk_terminal/discovery/finviz_view.py                                 16     10    38%
> gamestonk_terminal/discovery/seeking_alpha_model.py                         24      2    92%
> gamestonk_terminal/discovery/seeking_alpha_view.py                          22     15    32%
> gamestonk_terminal/discovery/short_interest_model.py                        44      0   100%
> gamestonk_terminal/discovery/short_interest_view.py                         26     18    31%
> gamestonk_terminal/discovery/simply_wallst_view.py                          13      7    46%
> gamestonk_terminal/discovery/spachero_view.py                               12      6    50%
> gamestonk_terminal/discovery/unusual_whales_view.py                         11      6    45%
> gamestonk_terminal/discovery/yahoo_finance_view.py                          23     16    30%
> gamestonk_terminal/due_diligence/__init__.py                                 0      0   100%
> gamestonk_terminal/due_diligence/business_insider_api.py                   207    207     0%
> gamestonk_terminal/due_diligence/dd_menu.py                                 78     78     0%
> gamestonk_terminal/due_diligence/financial_modeling_prep_api.py             21      6    71%
> gamestonk_terminal/due_diligence/finviz_api.py                              75     43    43%
> gamestonk_terminal/due_diligence/market_watch_api.py                       152    152     0%
> gamestonk_terminal/due_diligence/news_api.py                                25     25     0%
> gamestonk_terminal/due_diligence/quandl_api.py                              50     50     0%
> gamestonk_terminal/due_diligence/reddit_api.py                              38     38     0%
> gamestonk_terminal/feature_flags.py                                          9      0   100%
> gamestonk_terminal/fred/__init__.py                                          1      0   100%
> gamestonk_terminal/fred/fred_controller.py                                  66     45    32%
> gamestonk_terminal/fred/fred_view.py                                        89     56    37%
> gamestonk_terminal/fundamental_analysis/__init__.py                          0      0   100%
> gamestonk_terminal/fundamental_analysis/alpha_vantage_api.py               209    209     0%
> gamestonk_terminal/fundamental_analysis/business_insider_api.py             55     33    40%
> gamestonk_terminal/fundamental_analysis/fa_menu.py                         109    109     0%
> gamestonk_terminal/fundamental_analysis/financial_modeling_prep_api.py     300    251    16%
> gamestonk_terminal/fundamental_analysis/finviz_api.py                       19     19     0%
> gamestonk_terminal/fundamental_analysis/market_watch_api.py                 95     44    54%
> gamestonk_terminal/fundamental_analysis/yahoo_finance_api.py               115     68    41%
> gamestonk_terminal/fundamental_analysis/yield_curve_model.py                35      0   100%
> gamestonk_terminal/helper_funcs.py                                         271    159    41%
> gamestonk_terminal/main_helper.py                                          194    194     0%
> gamestonk_terminal/menu.py                                                  19      7    63%
> gamestonk_terminal/papermill/__init__.py                                     1      0   100%
> gamestonk_terminal/papermill/due_diligence_view.py                          28     20    29%
> gamestonk_terminal/papermill/econ_data_helper.py                            26     26     0%
> gamestonk_terminal/papermill/econ_data_view.py                              26     18    31%
> gamestonk_terminal/papermill/papermill_controller.py                        46     30    35%
> gamestonk_terminal/portfolio/__init__.py                                     0      0   100%
> gamestonk_terminal/portfolio/ally_api.py                                    32     32     0%
> gamestonk_terminal/portfolio/alp_api.py                                     58     58     0%
> gamestonk_terminal/portfolio/port_controller.py                            130    130     0%
> gamestonk_terminal/portfolio/portfolio_helpers.py                           58     58     0%
> gamestonk_terminal/portfolio/rh_api.py                                      86     86     0%
> gamestonk_terminal/prediction_techniques/__init__.py                         0      0   100%
> gamestonk_terminal/prediction_techniques/arima.py                          126    126     0%
> gamestonk_terminal/prediction_techniques/ets.py                            174    174     0%
> gamestonk_terminal/prediction_techniques/fbprophet.py                      113    113     0%
> gamestonk_terminal/prediction_techniques/knn.py                            118    118     0%
> gamestonk_terminal/prediction_techniques/neural_networks.py                305    272    11%
> gamestonk_terminal/prediction_techniques/pred_helper.py                     42     31    26%
> gamestonk_terminal/prediction_techniques/pred_menu.py                       76     76     0%
> gamestonk_terminal/prediction_techniques/regression.py                     130    130     0%
> gamestonk_terminal/prediction_techniques/sma.py                            115    115     0%
> gamestonk_terminal/reddit_helpers.py                                        37     37     0%
> gamestonk_terminal/res_menu.py                                              93     93     0%
> gamestonk_terminal/technical_analysis/__init__.py                            0      0   100%
> gamestonk_terminal/technical_analysis/finbrain_view.py                      26     26     0%
> gamestonk_terminal/technical_analysis/momentum.py                          187    187     0%
> gamestonk_terminal/technical_analysis/overlap.py                           115    115     0%
> gamestonk_terminal/technical_analysis/ta_controller.py                     110    110     0%
> gamestonk_terminal/technical_analysis/tradingview_view.py                   48     48     0%
> gamestonk_terminal/technical_analysis/trend_indicators.py                   98     98     0%
> gamestonk_terminal/technical_analysis/trendline_api.py                      26     26     0%
> gamestonk_terminal/technical_analysis/volatility.py                         44     44     0%
> gamestonk_terminal/technical_analysis/volume.py                             95     95     0%
> gamestonk_terminal/test_helper.py                                           29     29     0%
> gamestonk_terminal/thought_of_the_day.py                                    60     25    58%
> terminal.py                                                                168    168     0%
> tests/__init__.py                                                            0      0   100%
> tests/test_ba_finbrain_api.py                                                4      0   100%
> tests/test_dd_financial_modeling_prep_api.py                                 5      0   100%
> tests/test_dd_finviz_api.py                                                  5      0   100%
> tests/test_discovery_ark_api.py                                              4      0   100%
> tests/test_discovery_ark_model.py                                           23      0   100%
> tests/test_discovery_ark_view.py                                            15      0   100%
> tests/test_discovery_fidelity_api.py                                        15     15     0%
> tests/test_discovery_fidelity_model.py                                      14      0   100%
> tests/test_discovery_seeing_alpha_model.py                                  12      0   100%
> tests/test_discovery_short_interest_model.py                                20     20     0%
> tests/test_fa_business_insider_api.py                                        5      0   100%
> tests/test_fa_financial_modeling_prep_api.py                                11     11     0%
> tests/test_fa_market_watch_api.py                                            5      0   100%
> tests/test_fa_market_watch_api_unit.py                                      13     13     0%
> tests/test_fa_yahoo_finance_api.py                                           9      0   100%
> tests/test_fa_yield_curve_model.py                                          24     24     0%
> tests/test_fred_fred_view.py                                                12      0   100%
> tests/test_pred_neural_networks.py                                          18     18     0%
> tests/test_sentiment_reddit_api.py                                           4      4     0%
> tests/test_thought_of_the_day.py                                            17     17     0%
> --------------------------------------------------------------------------------------------
> TOTAL                                                                     6744   5756    15%
> ```

This is so cool! I didn't know about this. I'm assuming you used this https://coverage.readthedocs.io/en/coverage-5.5/ right?

I took it a bit easy during Easter. But once I'm done with Finviz additions + some README cleaning. I'll focus on adding tests + refactoring code, as then I think we don't have any critical feature.

**Review by DidierRLopes — APPROVED** [review]

**Comment by jmaslek** [comment]
So I know very little about this.  Does this mean that 15% of the unit tests fail?  Or just that 15% of the code runs?  If the latter -- is 15% bad?

**Review by jmaslek — APPROVED** [review]

**Comment by DidierRLopes** [comment]
> So I know very little about this. Does this mean that 15% of the unit tests fail? Or just that 15% of the code runs? If the latter -- is 15% bad?

This means (@aia correct me if I'm wrong) that from all our codebase, only 15% has unittests.

Personally, given that only @aia has been working on unit tests, and started mainly last week, I think that 15% is quite good.

Once I start helping out, and understanding better how to add unit tests, I think we'll be able to bump this number up quite fast.

**Comment by jmaslek** [comment]
I see.  I'm happy to add to as well, but I know nothing about them so will have to learn about the testing.

**Comment by DidierRLopes** [comment]
> I see. I'm happy to add to as well, but I know nothing about them so will have to learn about the testing.

Same for me. There will be some learning curve, but this is something good to learn! Test-driven development :)

**Comment by aia** [comment]
> 
> 
> > So I know very little about this. Does this mean that 15% of the unit tests fail? Or just that 15% of the code runs? If the latter -- is 15% bad?
> 
> This means (@aia correct me if I'm wrong) that from all our codebase, only 15% has unittests.

Correct.

The tests that we have execute only 15% of code lines in our code base.

**Comment by aia** [comment]
> This is so cool! I didn't know about this. I'm assuming you used this https://coverage.readthedocs.io/en/coverage-5.5/ right?

This is 

```
pip install pytest-cov
pytest -v --cov="$(pwd)" --cov-report html tests/
pytest -v --cov="$(pwd)" tests/
```

**Pull request merged**
