### PR TITLE
Adding pre-commit hooks for consistency.

### PR DESCRIPTION
**Pull request by qTipTip**
Hello!

I saw that you encourage people to run linters and formatting tools when committing. I think this should be enforced.
I have taken the liberty to configure pre-commit hooks for both `black` and `flake8` with the exclusions you mentioned in the root `README.md`. 

The diff is huge, as a lot of files contained trailing whitespaces which now has been stripped. In essence, the PR consists of

1. Added `pre-commit` to the `pyproject.toml`. 
2. An update to the README.md telling the user how to install the pre-commit hooks using `pre-commit install`.
3. Configuration file for pre-commit hooks: `.pre-commit-config.yaml`. 

🚀

### CODE REVIEW

**Comment by qTipTip** [comment]
Ironically, I didn't manage that. Will fix tomorrow 😅

**Comment by DidierRLopes** [comment]
> Ironically, I didn't manage that. Will fix tomorrow 😅

Nice! Good work!

**Comment by qTipTip** [comment]
@DidierRLopes , struggling to verify whether things are working without actually running the workflow. I guess I need to wait for one of you to approve?

**Comment by jmaslek** [comment]
should be able to run workflow now

**Comment by qTipTip** [comment]
Cheers! 

Still not able to trigger workflows myself, if that is what you ment @jmaslek , however I think I got it fixed now. Had to update the black revision. Was using an old version.

**Comment by qTipTip** [comment]
Seems to be some linting in the workflow that is not documented anywhere. I can add it to the pre-commits if I get an exhaustive list :)

**Comment by aia** [comment]
> Seems to be some linting in the workflow that is not documented anywhere. I can add it to the pre-commits if I get an exhaustive list :)

This is the list:
https://github.com/DidierRLopes/GamestonkTerminal/blob/main/.github/workflows/test.yml#L27

**Comment by aia** [comment]
You moved ` # type: ignore` to another line and that breaks mypy.

**Comment by qTipTip** [comment]
Ah, that is interesting. So `black` and `mypy` is conflicting then. I'll take a look after work.

**Comment by DidierRLopes** [comment]
> Ah, that is interesting. So `black` and `mypy` is conflicting then. I'll take a look after work.

Hey @qTipTip  are you still gonna fix this? We are excited about having this :) Thanks!

**Comment by qTipTip** [comment]
Hey! 

Yes, sorry - got tied up in some things over the weekend. 
Will look at this again after work.

**Comment by DidierRLopes** [comment]
> Hey!
> 
> Yes, sorry - got tied up in some things over the weekend.
> Will look at this again after work.

No problem, thank you for letting me know!

Do you think we could add a git-secrets to this? So that it checks whether by accident we are trying to commit our API keys?

I haven't used pre-commit hooks before, hence why asking about the feasibility of this :)

**Comment by qTipTip** [comment]
> > Hey!
> > Yes, sorry - got tied up in some things over the weekend.
> > Will look at this again after work.
> 
> No problem, thank you for letting me know!
> 
> Do you think we could add a git-secrets to this? So that it checks whether by accident we are trying to commit our API keys?
> 
> I haven't used pre-commit hooks before, hence why asking about the feasibility of this :)

Certainly. I'll see if I can find a suitable hook 👍

**Comment by qTipTip** [comment]
Closed in favor of #434. Sorry for the noise, got stuck in conflicting diffs from everywhere.

**Pull request closed without merging**
