### PR TITLE
Add new Screener menu

### PR DESCRIPTION
**Pull request by DidierRLopes**
See https://github.com/DidierRLopes/GamestonkTerminal/tree/screener-menu/gamestonk_terminal/screener
and
https://github.com/DidierRLopes/GamestonkTerminal/tree/screener-menu/gamestonk_terminal/screener/presets

Feel free to add nice presets :)

### CODE REVIEW

**Comment by jmaslek** [comment]
This is looking awesome 🥇

**Comment by jmaslek** [comment]
Also did you update requirements.txt?

**Comment by DidierRLopes** [comment]
> Also did you update requirements.txt?

Thanks for the reminder! Had that on my notes, but I would have very likely missed it ahah

**Comment by jmaslek** [comment]
boom this is really nice.  

In the README, where you have `#signal oversold`, I would personally enter the command that reproduces that result.  But other than that looks good.

**Review by jmaslek — APPROVED** [review]

**Comment by DidierRLopes** [comment]
> boom this is really nice.
> 
> In the README, where you have `#signal oversold`, I would personally enter the command that reproduces that result. But other than that looks good.

Agreed. Just added the example :)

**Comment by DidierRLopes** [comment]
@jmaslek should we delete `gainers` and `losers` from `discovery menu`?

**Comment by jmaslek** [comment]
I would leave it but have no strong preference.

**Comment by aia** [comment]
Very nice work Didier!
I'd leave gainers and losers in the discovery menu, but I would consolidate the implementation. Have separate views in different menus that work off a single model.

**Comment by DidierRLopes** [comment]
> Very nice work Didier!
> I'd leave gainers and losers in the discovery menu, but I would consolidate the implementation. Have separate views in different menus that work off a single model.

Thanks!

To be fair, the gainers and losers in discovery uses Yahoo finance rather than Finviz

**Pull request merged**
