### PR TITLE
add in option chains :)

### PR DESCRIPTION
**Pull request by jmaslek**
Addressing #272.

This PR adds in the ability to pull options chains from Tradier and it displays them in table form.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Really nice!!

You missed a `print("")` after the command runs.

The only thing I would say to improve the plot an additional step is:
1. Add an empty column on the left and on the right, of strike. In order to show better distinction between calls and puts.
2. Perhaps add green color on calls and red color for puts?

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Once this is merged,
- I'll refactor the options readme
- I'll add this command to features.md
- I'll add this PR to the ROADMAP

**Comment by jmaslek** [comment]
> 2. Perhaps add green color on calls and red color for puts?
I thought about this but honestly I am not sure how to do that with tabulate.  I also thought about printing Calls/Puts in colored above the table, but I am not sure if the table size will change based on the chain and the formatting gets messed up.

**Comment by DidierRLopes** [comment]
> > 2. Perhaps add green color on calls and red color for puts?
> 
> I thought about this but honestly I am not sure how to do that with tabulate.  I also thought about printing Calls/Puts in colored above the table, but I am not sure if the table size will change based on the chain and the formatting gets messed up.

Yea tabulate limits you a bit there. It would be good if you could add that extra delimiter, but if not It's still amazing, and feel free to merge it!

**Review by aia — APPROVED** [review]

**Pull request merged**
