### PR TITLE
update main readme

### PR DESCRIPTION
**Pull request by jmaslek**
Noticed a couple issues involving pmdarima -- which requires pip install not conda install.  Added that under the ModuleNotFoundError to avoid that.  Also added that it can be updated through pit pull which could close out an open issue.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
You were faster than me https://github.com/DidierRLopes/GamestonkTerminal/tree/address-bugs :)

**Comment by DidierRLopes** [comment]
I've also added a comment for Indian tickers working with ".NS" at end, which closes another ticket.

I've fixed the "view" cmd for indian tickers, because it was re-loading tickers from Alpha Vantage.

I'm now in the process of refactoring loading intraday data from yfinance because I found out that it's possible. Will also add a flag for before/after hours :)

**Comment by jmaslek** [comment]
Haha.  Your description is better.  Want to just add the message about the pmdarima and I will close/delete branch

**Comment by DidierRLopes** [comment]
Sweet! I've added your comments!

I'll do a PR soon

**Pull request closed without merging**
