### PR TITLE
Adds documentation for Docker in README

### PR DESCRIPTION
**Pull request by nodesocket**
Adds documentation for Docker in README.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Cheers! I'm working on a new README file, so this is definitely helpful.

Also, when running the docker we don't see the figures of matplotlib. Is there a workaround for this?

**Comment by nodesocket** [comment]
@DidierRLopes not sure on the `matplatlib`. I am seeing the following error but continues for `fbprophet` when building the Docker container. Is this expected?


```
  Building wheel for fbprophet (setup.py): started
  Building wheel for fbprophet (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ua9tj0ml
       cwd: /tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/setup.py", line 148, in <module>
      """
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/setup.py", line 48, in run
      build_models(target_dir)
    File "/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/setup.py", line 36, in build_models
      from fbprophet.models import StanBackendEnum
    File "/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/fbprophet/__init__.py", line 8, in <module>
      from fbprophet.forecaster import Prophet
    File "/tmp/pip-install-q11cpy0l/fbprophet_16e7723ed89f4d73b74710c45b78b963/fbprophet/forecaster.py", line 14, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  ```

**Comment by nodesocket** [comment]
Also, when running in the Docker container, the app appears to be exiting.

```
MacBook-Pro ➜  GamestonkTerminal git:(main) docker-compose up
Creating gamestonkterminal_gamestonkterminal_1 ... done
Attaching to gamestonkterminal_gamestonkterminal_1
gamestonkterminal_1  | 2021-03-02 23:50:30.806731: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
gamestonkterminal_1  | 2021-03-02 23:50:30.806783: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
gamestonkterminal_1  | /home/python/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
gamestonkterminal_1  |   return torch._C._cuda_getDeviceCount() > 0
gamestonkterminal_1  |
gamestonkterminal_1  | Welcome to Didier's Gamestonk Terminal
gamestonkterminal_1  |
gamestonkterminal_1  | What do you want to do?
gamestonkterminal_1  |    help        help to see this menu again
gamestonkterminal_1  |    quit        to abandon the program
gamestonkterminal_1  |
gamestonkterminal_1  |    clear       clear a specific stock ticker from analysis
gamestonkterminal_1  |    load        load a specific stock ticker for analysis
gamestonkterminal_1  |    view        view and load a specific stock ticker for technical analysis
gamestonkterminal_1  |
gamestonkterminal_1  | Stock: ?
gamestonkterminal_1  | Market CLOSED.
gamestonkterminal_1  |
gamestonkterminal_1  | Menus:
gamestonkterminal_1  |    disc        discover trending stocks, 	 e.g. map, sectors, high short interest
gamestonkterminal_1  |    sen         sentiment of the market, 	 from: reddit, stocktwits, twitter
gamestonkterminal_1  |
gamestonkterminal_1  | > Traceback (most recent call last):
gamestonkterminal_1  |   File "gamestonk_terminal.py", line 328, in <module>
gamestonkterminal_1  |     main()
gamestonkterminal_1  |   File "gamestonk_terminal.py", line 213, in main
gamestonkterminal_1  |     as_input = input('> ')
gamestonkterminal_1  | EOFError: EOF when reading a line
gamestonkterminal_gamestonkterminal_1 exited with code 1
```

**Comment by DidierRLopes** [comment]
Can you try:
```
docker build . 
```
and
```
docker run -it gamestonkterminal:dev 
```

I believe I had those issues with docker-compose, but when using docker only, didn't see them anymore.

**Comment by shadycuz** [comment]
@nodesocket The docker container doesn't have a screen to draw too. I left you a message in your original PR about that. You can pass in a screen but its kinda complicated. I don't think `docker-compose up` is the correct command. Try `docker-compose run`.

**Comment by ricleal** [comment]
Dummy question, how do you map directories? (if you want to modify the source code and see the result for example)
I tried with docker-compose and then just plain docker:
```
docker build -t gamestonkterminal .
docker run -it --rm -v /Users/ricardol/git/GamestonkTerminal:/home/python  gamestonkterminal bash
```
But the folder created in docker has more stuff....

Thanks in advance!

**Comment by DidierRLopes** [comment]
@nodesocket did you get docker-compose to run?

**Comment by DidierRLopes** [comment]
Closing this, as the main README already contains a Docker mention.

Once we publish docker, and/or have docker CI, we may add a section for it on the readme :)

Let me know if you disagree

**Pull request closed without merging**
