### PR TITLE
Better terminal with autocompletion + history

### PR DESCRIPTION
**Pull request by ricleal**
Hello all,

I just spent a few minutes prototyping a terminal using the `prompt-toolkit` (https://python-prompt-toolkit.readthedocs.io/).
We can do a proper autocompletion with nested options...

This was just 15 mins of my time. Let me know if you want to go ahead with this.

Thanks

### CODE REVIEW

**Comment by aia** [comment]
Very nice!

Could you update poetry too?

**Comment by aia** [comment]
I will merge this PR as is because this a highly requested feature.

I will fix poetry dependencies in the next PR. Need to add jupyter and mplfinance to the list too.

**Comment by ricleal** [comment]
Great! This was just a draft. I will complete this over the weekend and will submit another PR.

**Comment by arisliang** [comment]
What's the status of this? Is it available yet? I can't wait for the terminal history!

**Pull request merged**
