### PR TITLE
Update rm

### PR DESCRIPTION
**Pull request by jmaslek**
updated edit :: Roadmap :: ad fixed that port menu issue when the login failed (now just prints that the authentication fails with no menu update).

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Love to see this update, exciting things ahead!!

@aia also had nice ideas for portfolio analysis! Let's see if he can provide some ideas here. 

Feel free to tag yourself in features you want to add, we'll do this on a first-come first-serve basis :)

**Review by aia — APPROVED** [review]
This is great development, James!

**Comment by jmaslek** [comment]
Alright.  I was gonna start on the short term broker updates, so should I submit a new PR with dibs or just leave it as is?

**Comment by DidierRLopes** [comment]
For me you can leave it as it is. Go for it!

**Pull request merged**
