### PR TITLE
Cleanups – 𝐔𝐋𝐓𝐑𝐀 𝐌𝐎𝐃𝐄

### PR DESCRIPTION
**Pull request by akx**
Following up on the heels of #26, this PR does more than just "mechanical" cleaning by way of deduplicating code by extracting it into methods and modules.

Lots of plots, for example, were simply copy-pasted with only one field name changed. (In fact, some were mis-copy-pasted, using incorrect columns.)

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Hey @akx,

Can you have a look at this one? So that it merges cleanly?

Thanks man! Appreciate what you're doing here!

**Comment by akx** [comment]
@DidierRLopes Ready to review :)

**Comment by DidierRLopes** [comment]
Hey @akx  ,

Sorry, we had a major code re-architecture and bugfix PR being merged. @aia is helping me with CI/CD, as I don't have much experience in this area.

There's now a lot of conflicts with this. If you can fix them I would appreciate it massively, if you don't want to I understand and I'll fix it myself and merge it.

Either way let me know, thanks in advance and sorry for this taking so long!

**Comment by akx** [comment]
@DidierRLopes 😢  Sigh, I was hoping this (at 8 days old) would have been merged before #94 (7 hours old), because that PR introduced Black which basically just reorganizes _all_ of the code.

That basically means I will have to do basically all of the work here again.

**Comment by DidierRLopes** [comment]
@akx I completely understand where you come from, and I agree with you.

#94 has been merged before because is an overall rewrite of the code, and architecture. And the changes in there will bring the state of the terminal to a much better state (lots of bugfixes, improved ways of webscraping, new functionalities, colouring, to name a few). Aia is helping me keeping this repo in a good shape and in the project overall, he has experience with fast-growing projects, and lots of PRs and I trust him.

This is my fault, I should have merged this PR much earlier on, but have been working around poetry/dockers to make installation easy to everyone, given that I didn't know about these before, there was a bit of a learning curve there.

Anyway, I really like what you did here and I'll resolve the conflicts myself and merge it later today. So don't worry about it! Sorry for any inconvenience, this is overwhelming for me, and I'm still learning :)

**Comment by akx** [comment]
IMNSHO #94 should not have been merged as-is as a huge PR that intermingles new features with cleanup and refactoring in the first place – a PR with, say, one commit that moves the files into a package followed up by one commit that sets up Black and runs it would have been a manageable thing to rebase on... (cc @aia)

**Comment by DidierRLopes** [comment]
I was aware of the size of this PR, so I stand by that. @aia showed me on a skype call all the changes he's made, I've tested myself pretty much all commands, and reviewed it.

We all agree, from now on PRs will have to be much smaller. This was a one-off to steer the project in the right direction, and have a uniform codebase where everyone can contribute.

Sorry once again! I'll fix your PR later today once my workday finishes.

**Comment by DidierRLopes** [comment]
Took me some time, but all these improvements are now merged on the main code.

See #114 , #109 , #108 , #103 , #102 

On that basis I'll close this PR :)

**Pull request closed without merging**
