### PR TITLE
remove "fuck these guys" from Robinhood

### PR DESCRIPTION
**Pull request by sabujp**
I don't like Robinhood either, but not everyone who is going to use/see this in the future is going to have the same context. Let's keep the code clean and professional.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Good point! Thanks :)

**Comment by jmaslek** [comment]
Dang I was wondering how long that would last

**Comment by DidierRLopes** [comment]
> Dang I was wondering how long that would last

I was about to comment on that to remove once merged but find it funny and forgot ahah

**Comment by lolrenx** [comment]
could have changed to  "the best brokerage out there /s"

**Pull request merged**
