### PR TITLE
Exploratory Data Analysis Menu

### PR DESCRIPTION
**Pull request by DidierRLopes**
See https://github.com/DidierRLopes/GamestonkTerminal/pull/289/files#diff-2c691a7b3561ce9bf53b7943c6fdb70aea69ca4b7dfe15a492f544042b689e6e for more information

### CODE REVIEW

**Comment by aia** [comment]
Sorry we also got a ship stuck in a Suez canal

**Comment by DidierRLopes** [comment]
> Sorry we also got a ship stuck in a Suez canal

2021-03-26T100818Z_1496802128_RC2YIM9H5K6L_RTRMADP_3_EGYPT-SUEZCANAL-SHIP-SATELLITE-IMAGES_1616767480863

**Comment by DidierRLopes** [comment]
Captura de ecrã 2021-03-27, às 18 42 03

My poetry is playing up to install `detecta` library :(

**Comment by aia** [comment]
"Unusual route"
https://www.news.com.au/finance/economy/world-economy/catastrophic-oil-prices-spike-after-grounded-mega-ship-blocks-suez-canal/news-story/19d9322de92f703442b3aecccf8a7ffd

**Review by aia — APPROVED** [review]

**Pull request merged**
