### PR TITLE
Add CoinMarketCap + smallish refactor

### PR DESCRIPTION
**Pull request by jmaslek**
As per issue #374 , I added a menu for viewing the top n coins from CoinMarketCap API.  Also changed some file names and added docstrings where necessary.

### CODE REVIEW

**Comment by jmaslek** [comment]
@aia Any idea why the test fails?  I renamed one of the imports, but the test log has an old name?

**Comment by aia** [comment]
test-fail

**Comment by aia** [comment]
It is this code in mock.
```

class TestCoinGeckoAPI(TestCase):
    @mock.patch(
        "gamestonk_terminal.cryptocurrency.coin_api.CoinGeckoAPI.get_coin_market_chart_by_id"
    )
```

**Comment by jmaslek** [comment]
In the test .py file, there is no coin_api anymore, so I am confused why the log is saying that isn't defined.

**Review by aia — APPROVED** [review]

**Review by DidierRLopes — APPROVED** [review]
Niceee!

**Pull request merged**
