### PR TITLE
Enable median/quantiles around loop of Neural Networks predictions

### PR DESCRIPTION
**Pull request by DidierRLopes**
This aims to implement #240 .

As default I chose to plot the median prediction values. And filled the area between quantile 10 and 90%

Examples shown below:

loops

Captura de ecrã 2021-03-22, às 02 14 38

### CODE REVIEW

**Comment by Felixkruemel** [comment]
@DidierRLopes 
Does that work with backtesting? That would be great!

**Review by jmaslek — COMMENTED** [review]
Looks good!   noticing that the --loops aren't in the README usage.

Maybe not related to this PR, but if I enter a wrong date (under -e flag : assumed -e was epochs without looking at help )) then it quits the terminal, not just backs out to menu.
Screen Shot 2021-03-22 at 10 03 21 AM

**Comment by DidierRLopes** [comment]
> @DidierRLopes
> Does that work with backtesting? That would be great!

It does yes! :)

**Comment by DidierRLopes** [comment]
> Looks good! noticing that the --loops aren't in the README usage.
> 
> Maybe not related to this PR, but if I enter a wrong date (under -e flag : assumed -e was epochs without looking at help )) then it quits the terminal, not just backs out to menu.
> Screen Shot 2021-03-22 at 10 03 21 AM

Good finding!! I'll fix both of these now, cheers!

**Comment by DidierRLopes** [comment]
> > @DidierRLopes
> > Does that work with backtesting? That would be great!
> 
> It does yes! :)

Example:

ex1

ex2

**Review by jmaslek — APPROVED** [review]
Hell yeahhhh.  Looks great

**Comment by DidierRLopes** [comment]
> Hell yeahhhh. Looks great

I'll work today on adding a README on how to tune Neural Networks.

Otherwise this will happen https://www.reddit.com/r/GME/comments/makyk1/predicting_gme_price_for_the_week_using_ai_36279/
and we don't want to be responsible by bad YOLOs :D

**Comment by jmaslek** [comment]
Haha sounds good.  

Just curiously, is there a reason for not doing a train/test split or validation data on the NNs?

**Comment by DidierRLopes** [comment]
> Haha sounds good.
> 
> Just curiously, is there a reason for not doing a train/test split or validation data on the NNs?

Now it kind of does it. :)

The problem with just using train/test split is that this is time-series, and we rely on order. I'll write down about this on a new doc, and then you can comment against it if you agree or not

**Pull request merged**
