### PR TITLE
Do not use the ambiguous variable name 'l'

### PR DESCRIPTION
**Pull request by cclauss**
`l` and `1` look too much alike to a casual reader so `l` should not be used as a variable name.

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]
Agreed.

Quick question @cclauss and @aia. Using l_, s_, n_ before a variable comes from my C coding style. I'm now rewriting the code in a better way following #29 and #53, should I drop this s_,l_,n_ convention? If yes, now is the time to do so :)

**Comment by cclauss** [comment]
I believe that single-letter variable names make code look like it was written in the 1970s.

**Comment by DidierRLopes** [comment]
> I believe that single-letter variable names makes code look like it was written in the 1970s.

Yea, I didn't mean that single "l". That came from a copy-paste from stack-overflow very-likely.

I meant my variables being: l_args, s_ticker, d_submission. Where l_ is list, s_ string, d_ submission, and so on

**Comment by cclauss** [comment]
MUCH cooler to...

from [typing](https://docs.python.org/3/library/typing.html) import DIct, List
def my_func(args: List, ticker: str, submission: Dict) -> float:
    return 0.5

The big upside is that `mypy` will catch if you try to pass in a list instead of a dict or if you try to return a str.

**Comment by aia** [comment]
Type hinting is a big thing.

**Comment by DidierRLopes** [comment]
> MUCH cooler to...
> 
> from [typing](https://docs.python.org/3/library/typing.html) import DIct, List
> def my_func(args: List, ticker: str, submission: Dict) -> float:
> ` `return 0.5
> 
> The big upside is that `mypy` will catch if you try to pass in a list instead of a dict or if you try to return a str.

I'm on it!

**Pull request merged**
