### PR TITLE
Full cleanup to enable pylint, black. Move to a more standard project layout. Fix bugs. Add features.

### PR DESCRIPTION
**Pull request by aia**
Hopefully will be getting to small incremental changes from this point.

Checkout https://github.com/DidierRLopes/GamestonkTerminal/tree/refactor-2 for easier review.

Features:
- Colored output for Fidelity orders
- Colored output for Finviz analyst rating
- Randomized User-Agent for BeautifulSoup
- Papermill reports

Bug fixes:
- discovery/high_short_interest
- discovery/low_float
- discovery/get_analyst_price_targets
- fundamental_analysis/yahoo_info
- fundamental_analysis/yahoo_sustainability
- fundamental_analysis/yahoo_earnings_calendar
- fundamental_analysis/business_insider_management
- due_diligence/financial_modeling_prep_api

### CODE REVIEW

**Comment by mjt91** [comment]
any reason why to use pylint and flake8? Personally I am a big fan of flake8's out of the box linting. pylint uses a very bloated configuration, while flake8 is easier to implement.

**Comment by aia** [comment]
> 
> 
> any reason why to use pylint and flake8? Personally I am a big fan of flake8's out of the box linting. pylint uses a very bloated configuration, while flake8 is easier to implement.

Pylint is more comprehensive. Both pylint and flake8 will be enforced:

      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pylint **/*.py

**Comment by akx** [comment]
I think overly enforcing a Pylint configuration might not be a good idea. We're here to watch stonks go up and write code for humans to use, not to make a linter happy.

**Comment by mjt91** [comment]
> I think overly enforcing a Pylint configuration might not be a good idea. We're here to watch stonks go up and write code for humans to use, not to make a linter happy.

This. I propose flake8 usage, since it yields to best of two worlds.

**Comment by aia** [comment]
Humans are happy when the code is working.

The code is working when linting is clean. You can tune or disable it for specific lines where you think you know better than the linter.

Linter is really not that much of a bother. I don't recall the last time I worked on a project where linting was not enforced. I am, personally, writing code a lot faster with linter.

If people struggle too much - we will tone it down.

**Review by DidierRLopes — APPROVED** [review]
Amazing work!

Looks good to me! Let's see if from now on we have smaller PRs :) But I like the re-structure of the code, should have been done like this from the start.

**Pull request merged**
