### PR TITLE
Fix US Market Holidays issue

### PR DESCRIPTION
**Pull request by noufal85**
Refer to https://github.com/DidierRLopes/GamestonkTerminal/issues/248
 #248

### CODE REVIEW

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Nice, thanks.

However, I've tested this with prediction menu and this introduced a bug there. That is because the prediction menu uses `get_next_stock_market_days`

Can you try to fix it, in order to accept it?

**Comment by noufal85** [comment]
> Nice, thanks.
> 
> However, I've tested this with prediction menu and this introduced a bug there. That is because the prediction menu uses `get_next_stock_market_days`
> 
> Can you try to fix it, in order to accept it?

Sorry , Please hold - I am testing

**Comment by noufal85** [comment]
> > Nice, thanks.
> > However, I've tested this with prediction menu and this introduced a bug there. That is because the prediction menu uses `get_next_stock_market_days`
> > Can you try to fix it, in order to accept it?
> 
> Sorry , Please hold - I am testing

All looks good Now - Sorry about that mistake , Amazing package

**Comment by DidierRLopes** [comment]
> > > Nice, thanks.
> > > However, I've tested this with prediction menu and this introduced a bug there. That is because the prediction menu uses `get_next_stock_market_days`
> > > Can you try to fix it, in order to accept it?
> > 
> > 
> > Sorry , Please hold - I am testing
> 
> All looks good Now - Sorry about that mistake , Amazing package

Perfect! Thank you, that definitely makes my life easier!

I'm gonna go to bed because it's quite late here and gotta work tomorrow, but will try to review this and merge during my lunch break.

Cheers, and keep contributing to the repo!

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
