### PR TITLE
Update config_terminal.py

### PR DESCRIPTION
**Pull request by ricksfunhouse**
trying to update with the API data

### CODE REVIEW

**Comment by jmaslek** [comment]
The API keys are unique to everyone.  This should be edited on your personal environment.

**Comment by jmaslek** [comment]
You should delete this branch ASAP.  Your personal API keys are now available to anyone.

**Comment by DidierRLopes** [comment]
I've changed the title to hide this PR. I can't remove it myself due to git philosophy that nothing is hidden.

However, @ricksfunhouse you can send an e-mail to support@github.com and explain that you want to delete this PR because by accident you created a Pull Request where you share your own unique personal keys.

**Comment by ricksfunhouse** [comment]
Jinkies! What a mess.. sorry about the confusion yall. I think I removed everything with personal APIs. Thanks for the help

**Comment by DidierRLopes** [comment]
No worries! The issue is that you can still see your changes with the API keys. The worst that can happen is someone using your API keys for you and reaching the limit requests earlier on.

**Pull request closed without merging**
