### PR TITLE
Non-breaking import readline

### PR DESCRIPTION
**Pull request by comradesmith**
Importing readline will improve user experience by letting users do a few things:
- easily access their command history from the current session using up/down arrows
- reverse history search with crtl+r
- use emacs keybindings (ctrl+a, etc)

I'll add this to the PR description, thanks!

Attempted in #77 and #80. However there were issues due to the lack of availability of readline in windows environments.

If merged this will add readline support _where available_, improving the UX on those platforms. There is also room to later import a solution available on windows in the `except` block.

### CODE REVIEW

**Comment by comradesmith** [comment]
gotta run linter brb

**Comment by comradesmith** [comment]
> gotta run linter brb

done :)

**Comment by aia** [comment]
What is that going to accomplish?

**Comment by comradesmith** [comment]
> What is that going to accomplish?

Importing readline will improve user experience by letting users do a few things:
- easily access their command history from the current session using up/down arrows
- reverse history search with crtl+r
- use emacs keybindings (ctrl+a, etc)

I'll add this to the PR description, thanks!

**Comment by aia** [comment]
How does it compare to Prompt-Toolkit that has been implemented here https://github.com/DidierRLopes/GamestonkTerminal/pull/142?

**Comment by comradesmith** [comment]
> How does it compare to Prompt-Toolkit that has been implemented here #142?

Actually yeah that is better but its behind a feature flag so I wasn't aware. I'll close this and open a PR marking that FF as on so we can start to discuss making that the default behaviour as it is really nice

**Comment by comradesmith** [comment]
> How does it compare to Prompt-Toolkit that has been implemented here #142?

Hi @aia @DidierRLopes I have re-opened this because it has many of the benefits of #142, but it is compatible with the prediction tools which had a bug with prompt toolkit (tracked in #174). So I think this is a good compromise to get some (but not all) UX improvements in front of users without impacting the prediction tools

**Review by aia — CHANGES_REQUESTED** [review]
I'm not sure implementing multiple unfinished approaches to the same problem is the way to go.

This PR is about a UI feature and need to have a feature flag.

Also this PR adds an optional dependency and does not update poetry/requirements.

**Comment by DidierRLopes** [comment]
I think #190 has addressed this in a nice way, I'll close this PR on that basis.

**Pull request closed without merging**
